import GlobalStyle from '../styles/global'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Menu from '../components/menu'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin-Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle/>
      <body className={inter.className}>
        <div className="main">
          <Navbar />
          <div className="container">
            <div className="menuContainer">
              <Menu />
            </div>
            <div className="contentContainer">
              {children}
            </div>
          </div>
        <Footer />
        </div>
        
      </body>
    </html>
  )
}
