import GlobalStyle from '../styles/global'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle/>
      <div className="main">
        {/* <Navbar /> */}
        <div className="container">
          <div className="menuContainer">
            {/* <Menu /> */}
          </div>
          {/* <div className="contentContainer">
            <QueryClientProvider client={queryClient}>
              <Outlet />
            </QueryClientProvider>
          </div> */}
        </div>
        <Footer />
      </div>
      <body className={inter.className}>
      <Navbar />
        {children}
      </body>
    </html>
  )
}
